version: "3"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  sensor-simulators:
    build: ./sensor-simulators
    depends_on:
      - mqtt-broker

  aeb-service:
    build: ./services/aeb-service
    depends_on:
      - mqtt-broker

  fcw-service:
    build: ./services/fcw-service
    depends_on:
      - mqtt-broker

  lka-service:
    build: ./services/lka-service
    depends_on:
      - mqtt-broker

  daw-service:
    build: ./services/daw-service
    depends_on:
      - mqtt-broker

  tpms-service:
    build: ./services/tpms-service
    depends_on:
      - mqtt-broker

  gatekeeper:
    build: ./gatekeeper
    depends_on:
      - mqtt-broker

  actuator-mock:
    build: ./actuator-mock
    depends_on:
      - mqtt-broker
